/**
 * This file is used to layout the sibling page.
 * You can define HTML structure of how your page will look like or divided in parts.
 */
import "../assets/scss/style.scss";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="container">
          <div className="d-flex">
            <Sidebar />
            <div className="d-flex flex-col flex-grow-1">
              <Header />
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
